spring:
  application:
    name: ProductManager
  datasource:
    url: jdbc:mariadb://localhost:3306/product-manager
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

