spring:
  application:
    name: ProductManager
  datasource:
    url: jdbc:mariadb://localhost:3307/ProductManager
    username: root
    password: admin123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

